#!/bin/bash
# chkconfig: 2345 20 80
# description: Description comes here....

# Source function library.
#. /etc/init.d/functions

start() {
   # code to start app comes here 
   # example: daemon program_name &
   /usr/bin/python3 /home/matt/app/biotech/utils/pipePackage/pipeFull.py&
}

stop() {
   # code to stop app comes here 
   # example: killproc program_name
   kill -9 `cat /var/run/user/pipeline.pid`
   if [ "$?" -ne "0" ]
   then
      echo "Something went wrong while killing the pipeline"
   else
      echo "Pipeline brutally stopped."
   fi

}

case "$1" in 
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      stop
      start
      ;;
   *)
      echo "Usage: $0 {start|stop|restart}"
esac

exit 0 
