version: "3"
    
services:
  monitor:
    container_name: monitor
    image: accetto/xubuntu-vnc-novnc:latest
    #image: xubunutu-novnc-biotech:latest
    user: root:root
    volumes:
      - type: bind
        source: ../../scripts
        target: /home/headless/Desktop/Biotech
    #  - type: bind
    #    source: ../../scripts/try.sh
    #    target: /home/headless/.bashrc
    stdin_open: true
    tty: true
    #healthcheck: 
    #test: [CMD, "sh", "-c", "echo headless | sudo -S apt-get update"] 
    #run: "sh -c \"echo headless | sudo -S apt-get update\""
    command: "--wait"
      #- sh -c "echo headless | sudo -S apt-get update"  
      #- "--wait"
    #command: bash -c 'sudo -S <<< "headless"  apt-get update && sudo -S apt-get install netcat'
    ports:
      - "25901:5901"
      - "26901:6901"
    restart: always


  busco:
    container_name: busco
    image: ezlabgva/busco:v5.4.3_cv1 
    restart: always
    stdin_open: true
    tty: true
  
  corset:
    container_name: corset
    image: pegi3s/soapdenovo2 
    restart: always
    stdin_open: true
    tty: true

  detonate:
    container_name: detonate
    image: nanozoo/detonate
    restart: always
    stdin_open: true
    tty: true

  fastqc:
    container_name: fastqc
    image: staphb/fastqc:latest
    restart: always
    #command: ["/bin/bash"]
    stdin_open: true
    tty: true

  python:
    container_name: python
    image: python:3.9-alpine
    restart: always
    stdin_open: true
    tty: true

  salmon:
    container_name: salmon
    image: combinelab/salmon 
    restart: always
    stdin_open: true
    tty: true

  soapdenovo:
    container_name: soapdenovo
    image: pegi3s/soapdenovo2 
    restart: always
    stdin_open: true
    tty: true

  spades:
    container_name: spades
    image: staphb/spades:latest
    restart: always
    stdin_open: true
    tty: true

  transabyss:
    container_name: transabyss
    image: ss93/transabyss-2.0.1
    restart: always
    stdin_open: true
    tty: true
 
  trimmomatic:
    container_name: trimmomatic
    image: staphb/trimmomatic:latest
    restart: always
    stdin_open: true
    tty: true

  trinity:
    container_name: trinityrnaseq
    image: trinityrnaseq/trinityrnaseq
    restart: always
    expose:
    - "22"
    stdin_open: true
    tty: true
  
  
networks:
  test:
    driver: bridge