version: "3"
    
services:

  monitor:
    container_name: monitor
    image: accetto/xubuntu-vnc-novnc:latest
    #image: xubuntu-vnc-novnc:sapienza
    #image: xubunutu-novnc-biotech:latest
    #volumes:
      #- type: bind
        #source: /home/matt/app/biotech
        #target: /home
    ports:
      - "25901:5901"
      - "26901:6901"
    restart: always


  python:
    container_name: python
    image: python:3.9-alpine
    restart: always
    stdin_open: true
    tty: true

  spades:
    container_name: spades
    image: staphb/spades:latest
    restart: always
    stdin_open: true
    tty: true

  fastqc:
    container_name: fastqc
    image: staphb/fastqc:latest
    restart: always
    #command: ["/bin/bash"]
    stdin_open: true
    tty: true

  trimmomatic:
    container_name: trimmomatic
    image: staphb/trimmomatic:latest
    restart: always
    stdin_open: true
    tty: true