version: "3.8"
    
services:

  monitor:
    container_name: monitor
    #image: accetto/xubuntu-vnc-novnc:latest
    image: xubuntu-novnc-biotech:latest
    user: root:root
    volumes:
      - type: bind
        source: ../../scripts
        #source: /opt/pipeline/var/run
        target: /home/headless/Desktop/Biotech
    stdin_open: true
    tty: true   
    ports:
      - "25901:5901"
      - "26901:6901"
    restart: always

  biopython:
    container_name: biopython
    image: biocontainers/biopython:v1.73dfsg-1-deb-py3_cv1
    restart: always
    volumes:
      - type: bind
        source: ../../scripts
        target: /data
    stdin_open: true
    tty: true

  busco:
    container_name: busco
    image: ezlabgva/busco:v5.4.3_cv1 
    restart: always
    volumes:
      - type: bind
        source: ../../scripts
        target: /busco_wd
    stdin_open: true
    tty: true
  
  cdhit:
    container_name: cdhit
    image: chrishah/cdhit:v4.8.1
    restart: always
    volumes:
      - type: bind
        source: ../../scripts
        target: /in
    stdin_open: true
    tty: true

  corset:
    container_name: corset
    image: mdiblbiocore/corset:1.0.9
    restart: always
    volumes:
      - type: bind
        source: ../../scripts
        target: /compbio
    stdin_open: true
    tty: true

  fastqc:
    container_name: fastqc
    image: staphb/fastqc:latest
    restart: always
    volumes:
      - type: bind
        source: ../../scripts
        target: /data
    stdin_open: true
    tty: true

  hisat:
    container_name: hisat
    image: nanozoo/hisat2:latest
    restart: always
    volumes:
      - type: bind
        source: ../../scripts
        target: /data
    stdin_open: true
    tty: true

  spades:
    container_name: spades
    image: staphb/spades:latest
    restart: always
    volumes:
      - type: bind
        source: ../../scripts
        target: /data
    stdin_open: true
    tty: true

  transdecoder:
    container_name: transdecoder
    image: biocrusoe/transdecoder
    restart: always
    volumes:
      - type: bind
        source: ../../scripts
        target: /data
    stdin_open: true
    tty: true
 
  trimmomatic:
    container_name: trimmomatic
    image: staphb/trimmomatic:latest
    restart: always
    volumes:
      - type: bind
        source: ../../scripts
        target: /data
    stdin_open: true
    tty: true
    
networks:
  bionet:
    driver: bridge